use_frameworks!

platform :ios, '8.0'

target 'PodLibCreateModule_Example' do
  pod 'PodLibCreateModule', :path => '../'

  target 'PodLibCreateModule_Tests' do
    inherit! :search_paths

    
  end
end
