use_frameworks!

platform :ios, '9.3'

target 'PodLibCreateModule_Example' do
  pod 'PodLibCreateModule', :path => '../'

  target 'PodLibCreateModule_Tests' do
    inherit! :search_paths

    
  end
end
